"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['main.py']
DATA_FILES = ["./config/config.json", "./config/voice_config.json", "./example", "./tts.xml"]
OPTIONS = {
    "iconfile": "./icon/tts.png"
}

setup(
    name="FreeTTS",
    version="1.0",
    author="Fisher1008",
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
